@extends('layouts.app')
@section('title', 'Scan barang')
@section('content')
<div class="page-head"><div><div class="page-eyebrow">OPERASIONAL · PEMINDAIAN</div><h1 class="page-title">Scan barang</h1><p class="page-subtitle">Gunakan scanner USB/Bluetooth yang mengetik kode lalu Enter, atau aktifkan kamera untuk membaca label.</p></div></div>
<div class="row g-3 align-items-start" data-scan-page>
    <div class="col-xl-5"><div class="surface"><div class="surface-head"><h2>Baca kode barang</h2></div><div class="surface-body">
        <form action="{{ route('scan.index') }}" method="get" id="scan-form"><label class="form-label" for="scan-code">Kode pada label</label><div class="input-group"><input id="scan-code" name="code" class="form-control form-control-lg" value="{{ $code }}" placeholder="Arahkan scanner ke label" maxlength="80" autocomplete="off" required autofocus><button class="btn btn-primary" type="submit">Cari</button></div><p class="form-hint mt-2 mb-0">Scanner biasanya mengirim Enter otomatis. Jika tidak, tekan tombol Cari.</p></form>
        <div class="scan-divider"><span>ATAU</span></div>
        <div class="d-flex flex-wrap gap-2"><button type="button" class="btn btn-outline-primary" id="camera-start"><i class="bi bi-camera me-1"></i> Buka kamera</button><button type="button" class="btn btn-outline-secondary d-none" id="camera-stop">Tutup kamera</button></div>
        <p id="camera-status" class="form-hint mt-2 mb-0" role="status" aria-live="polite">Kamera hanya aktif saat tombol ditekan.</p>
        <div id="camera-reader" class="scanner-reader mt-3" aria-label="Pratinjau kamera pemindai"></div>
    </div></div></div>
    <div class="col-xl-7">
        @if($code !== '' && !$item)<div class="surface"><div class="surface-body"><div class="page-eyebrow">KODE TIDAK DITEMUKAN</div><h2 class="h5">Tidak ada barang untuk “{{ $code }}”</h2><p class="text-secondary mb-0">Periksa kode SKU pada katalog atau scan ulang label yang benar.</p></div></div>
        @elseif($item)
        <div class="surface mb-3"><div class="surface-head"><h2>Barang ditemukan</h2><span class="badge-status">{{ $item->location->name }}</span></div><div class="surface-body"><div class="page-eyebrow">{{ $item->sku }}</div><h2 class="scan-item-name">{{ $item->name }}</h2><div class="d-flex flex-wrap gap-4 mt-3"><div><div class="stat-label">{{ $item->location->workflow === 'loan' ? 'Tersedia' : 'Stok saat ini' }}</div><strong class="fs-4">{{ $item->available }}</strong> {{ $item->unit }}</div><div><div class="stat-label">Status katalog</div><strong>{{ $item->is_active ? 'Aktif' : 'Nonaktif' }}</strong></div></div>@can('items.view')<a class="btn btn-sm btn-outline-secondary mt-3" href="{{ route('items.label', $item) }}">Cetak label</a>@endcan</div></div>
        @if($item->location->workflow === 'loan')
            @can('loans.handover')<div class="surface"><div class="surface-head"><h2>Serah terima & pengembalian</h2><span class="form-hint">{{ $loans->count() }} proses</span></div><div class="table-responsive"><table class="table"><thead><tr><th>Pinjaman</th><th>Jumlah</th><th>Jatuh tempo</th><th>Aksi</th></tr></thead><tbody>@forelse($loans as $loan)<tr><td>@if(auth()->user()->can('loans.view-all') || (auth()->user()->can('loans.create') && $loan->requester_id === auth()->id()))<a href="{{ route('loans.show', $loan) }}">#{{ $loan->id }} · {{ $loan->requester->name }}</a>@else #{{ $loan->id }} · {{ $loan->requester->name }} @endif<div class="form-hint">{{ $loan->status === 'approved' ? 'Disetujui' : 'Sedang dipinjam' }}</div></td><td>{{ $loan->quantity }} {{ $item->unit }}</td><td>{{ $loan->due_on->format('d/m/Y') }}</td><td>@if($loan->status === 'approved')<form method="post" action="{{ route('loans.transition', [$loan, 'issue']) }}">@csrf<button class="btn btn-sm btn-primary" type="submit">Serahkan</button></form>@else<form method="post" action="{{ route('loans.transition', [$loan, 'return']) }}">@csrf<input type="text" class="form-control form-control-sm mb-2" name="note" placeholder="Kondisi saat kembali" aria-label="Kondisi saat kembali" maxlength="2000"><button class="btn btn-sm btn-outline-primary" type="submit">Terima kembali</button></form>@endif</td></tr>@empty<tr><td colspan="4" class="empty-state">Tidak ada pinjaman yang siap diproses untuk alat ini.</td></tr>@endforelse</tbody></table></div></div>@else<div class="surface"><div class="surface-body text-secondary">Anda tidak memiliki izin serah terima di lokasi ini.</div></div>@endcan
        @else
            @can('requests.fulfill')<div class="surface mb-3"><div class="surface-head"><h2>Permintaan disetujui</h2><span class="form-hint">{{ $stockRequests->count() }} permintaan</span></div><div class="table-responsive"><table class="table"><thead><tr><th>Permintaan</th><th>Jumlah</th><th>Aksi</th></tr></thead><tbody>@forelse($stockRequests as $stockRequest)<tr><td>@if(auth()->user()->can('requests.view-all') || (auth()->user()->can('requests.create') && $stockRequest->requester_id === auth()->id()))<a href="{{ route('requests.show', $stockRequest) }}">#{{ $stockRequest->id }} · {{ $stockRequest->requester->name }}</a>@else #{{ $stockRequest->id }} · {{ $stockRequest->requester->name }} @endif</td><td>{{ $stockRequest->quantity }} {{ $item->unit }}</td><td><form method="post" action="{{ route('requests.transition', [$stockRequest, 'fulfill']) }}">@csrf<button type="submit" class="btn btn-sm btn-primary">Keluarkan barang</button></form></td></tr>@empty<tr><td colspan="3" class="empty-state">Tidak ada permintaan yang siap dipenuhi.</td></tr>@endforelse</tbody></table></div></div>@endcan
            @can('stock.adjust')
                @if($item->is_active)<div class="surface"><div class="surface-head"><h2>Stok masuk / keluar langsung</h2></div><form action="{{ route('scan.stock') }}" method="post" class="surface-body row g-3">@csrf<input type="hidden" name="item_id" value="{{ $item->id }}"><div class="col-sm-6"><label class="form-label" for="direction">Arah mutasi</label><select id="direction" name="direction" class="form-select" required><option value="in" @selected(old('direction') === 'in')>Masuk · tambah stok</option><option value="out" @selected(old('direction') === 'out')>Keluar · kurangi stok</option></select></div><div class="col-sm-6"><label class="form-label" for="quantity">Jumlah ({{ $item->unit }})</label><input id="quantity" name="quantity" type="number" min="1" max="1000000" value="{{ old('quantity', 1) }}" class="form-control" required></div><div class="col-12"><label class="form-label" for="note">Alasan / nomor dokumen</label><input id="note" name="note" class="form-control" value="{{ old('note') }}" maxlength="255" required><p class="form-hint mt-1 mb-0">Untuk permintaan yang sudah disetujui, gunakan tombol Keluarkan barang pada daftar di atas.</p></div><div class="col-12"><button class="btn btn-primary" type="submit">Catat mutasi stok</button></div></form></div>@endif
            @endcan
        @endif
        @else<div class="surface"><div class="surface-body empty-state"><i class="bi bi-upc-scan"></i>Hasil scan dan aksi barang akan muncul di sini.</div></div>@endif
    </div>
</div>
@endsection
