@extends('layouts.app')
@section('title', 'Peminjaman #'.$loan->id)
@section('content')
<div class="page-head"><div><div class="page-eyebrow">{{ strtoupper($loan->item->location->name) }} · PEMINJAMAN #{{ $loan->id }}</div><h1 class="page-title">{{ $loan->item->name }}</h1><p class="page-subtitle">Diajukan {{ $loan->created_at->format('d/m/Y H:i') }} oleh {{ $loan->requester->name }}.</p></div><a href="{{ route('loans.index') }}" class="btn btn-outline-secondary">Kembali</a></div>
<div class="row g-3"><div class="col-lg-7"><div class="surface"><div class="surface-head"><h2>Detail peminjaman</h2><span class="badge-status">{{ ['submitted'=>'Diajukan','approved'=>'Disetujui','issued'=>'Dipinjam','returned'=>'Dikembalikan','rejected'=>'Ditolak'][$loan->status] }}</span></div><div class="surface-body"><dl class="row mb-0"><dt class="col-sm-4">Kode alat</dt><dd class="col-sm-8">{{ $loan->item->sku }}</dd><dt class="col-sm-4">Jumlah</dt><dd class="col-sm-8">{{ $loan->quantity }} {{ $loan->item->unit }}</dd><dt class="col-sm-4">Tanggal pakai</dt><dd class="col-sm-8">{{ $loan->needed_from->format('d/m/Y') }}</dd><dt class="col-sm-4">Batas kembali</dt><dd class="col-sm-8">{{ $loan->due_on->format('d/m/Y') }}</dd><dt class="col-sm-4">Keperluan</dt><dd class="col-sm-8">{{ $loan->purpose }}</dd>@if($loan->rejection_note)<dt class="col-sm-4">Alasan ditolak</dt><dd class="col-sm-8">{{ $loan->rejection_note }}</dd>@endif @if($loan->return_note)<dt class="col-sm-4">Catatan kembali</dt><dd class="col-sm-8">{{ $loan->return_note }}</dd>@endif</dl></div></div>
@if($loan->status === 'submitted' && auth()->user()->can('loans.approve'))<div class="surface mt-3"><div class="surface-head"><h2>Keputusan petugas</h2></div><div class="surface-body d-flex flex-wrap gap-2"><form method="post" action="{{ route('loans.transition', [$loan, 'approve']) }}">@csrf<button class="btn btn-primary" type="submit">Setujui</button></form><form method="post" action="{{ route('loans.transition', [$loan, 'reject']) }}" class="d-flex gap-2 flex-wrap">@csrf<input class="form-control" name="note" placeholder="Alasan penolakan" aria-label="Alasan penolakan" required><button class="btn btn-outline-danger" type="submit">Tolak</button></form></div></div>@endif
@if($loan->status === 'approved' && auth()->user()->can('loans.handover'))<div class="surface mt-3"><div class="surface-head"><h2>Serah terima</h2></div><div class="surface-body"><p class="form-hint">Stok tersedia saat ini: {{ $loan->item->available }} {{ $loan->item->unit }}.</p><form method="post" action="{{ route('loans.transition', [$loan, 'issue']) }}">@csrf<button class="btn btn-primary" type="submit">Catat alat diserahkan</button></form></div></div>@endif
@if($loan->status === 'issued' && auth()->user()->can('loans.handover'))<div class="surface mt-3"><div class="surface-head"><h2>Pengembalian</h2></div><form method="post" action="{{ route('loans.transition', [$loan, 'return']) }}" class="surface-body">@csrf<label for="note" class="form-label">Kondisi / catatan pengembalian</label><textarea id="note" name="note" class="form-control mb-3" rows="2"></textarea><button class="btn btn-primary" type="submit">Catat pengembalian</button></form></div>@endif
</div><div class="col-lg-5"><div class="surface"><div class="surface-head"><h2>Jejak proses</h2></div><div class="surface-body"><ol class="timeline-plain"><li><strong>Diajukan</strong><div class="form-hint">{{ $loan->created_at->format('d/m/Y H:i') }} · {{ $loan->requester->name }}</div></li>@if($loan->approved_at)<li><strong>Disetujui</strong><div class="form-hint">{{ $loan->approved_at->format('d/m/Y H:i') }} · {{ $loan->approver?->name }}</div></li>@endif @if($loan->issued_at)<li><strong>Diserahkan</strong><div class="form-hint">{{ $loan->issued_at->format('d/m/Y H:i') }} · {{ $loan->issuer?->name }}</div></li>@endif @if($loan->returned_at)<li><strong>Dikembalikan</strong><div class="form-hint">{{ $loan->returned_at->format('d/m/Y H:i') }} · {{ $loan->receiver?->name }}</div></li>@endif @if($loan->status === 'rejected')<li><strong>Ditolak</strong><div class="form-hint">{{ $loan->updated_at->format('d/m/Y H:i') }}</div></li>@endif</ol></div></div></div></div>
@endsection
