@extends('layouts.app')
@section('title', 'Checklist '.$location->name)
@section('content')
<div class="page-head"><div><div class="page-eyebrow">{{ strtoupper($location->type->name) }} · {{ $location->scan_code }}</div><h1 class="page-title">Checklist {{ $location->name }}</h1><p class="page-subtitle">{{ today()->translatedFormat('l, d F Y') }} · Periksa setiap peralatan yang tersimpan di lokasi ini.</p></div><div class="d-flex flex-wrap gap-2"><a class="btn btn-outline-secondary" href="{{ route('inspections.label', $location) }}">Barcode lokasi</a><a class="btn btn-outline-secondary" href="{{ route('inspections.index') }}">Semua lokasi</a></div></div>
@if($latestInspection)
    <div class="surface mb-3"><div class="surface-body d-flex flex-wrap align-items-center justify-content-between gap-2"><div><div class="page-eyebrow">PEMERIKSAAN TERAKHIR</div><strong>{{ $latestInspection->created_at->format('d/m/Y H:i') }}</strong> · {{ $latestInspection->inspector->name }}</div><span class="badge-status {{ $latestInspection->status === 'ok' ? '' : 'is-warm' }}">{{ $latestInspection->status === 'ok' ? 'Sesuai' : 'Perlu tindak lanjut' }}</span></div></div>
@endif
<div class="surface mb-4"><div class="surface-head"><h2>Daftar peralatan</h2><span class="form-hint">{{ $items->count() }} jenis · satu barcode untuk lokasi</span></div>
    @if(!$location->is_active)<div class="surface-body text-secondary">Lokasi nonaktif. Riwayat tetap dapat dilihat, tetapi pengecekan baru tidak dapat dicatat.</div>
    @elseif($items->isEmpty())<div class="surface-body empty-state">Belum ada peralatan aktif. Tambahkan barang ke lokasi ini sebelum mencatat pengecekan.</div>
    @elseif(!auth()->user()->can('checks.perform'))<div class="surface-body"><p class="text-secondary">Akun ini dapat melihat daftar dan riwayat, tetapi tidak dapat mencatat pengecekan.</p>@foreach($items as $item)<div class="checklist-row py-2 d-flex justify-content-between gap-2"><strong>{{ $item->name }}</strong><span>{{ $item->quantity }} {{ $item->unit }}</span></div>@endforeach</div>
    @else
    <form method="post" action="{{ route('inspections.store', $location) }}" class="surface-body">@csrf
        <p class="form-hint mb-3">Isi jumlah yang ditemukan dan kondisi setiap alat. Jika jumlah berbeda atau kondisi rusak, catatan wajib diisi. Hasil ini tidak mengubah jumlah standar barang.</p>
        @foreach($items as $item)
            <div class="checklist-row row g-2 align-items-end py-3"><div class="col-lg-4"><div class="form-hint">{{ sprintf('%02d', $loop->iteration) }} · {{ $item->sku }}</div><strong>{{ $item->name }}</strong></div><div class="col-6 col-sm-3 col-lg-1"><div class="form-label">Standar</div><div class="py-2">{{ $item->quantity }} {{ $item->unit }}</div></div><div class="col-6 col-sm-3 col-lg-2"><label class="form-label" for="actual-{{ $item->id }}">Ditemukan</label><input class="form-control" id="actual-{{ $item->id }}" type="number" name="rows[{{ $item->id }}][actual_quantity]" min="0" max="1000000" value="{{ old('rows.'.$item->id.'.actual_quantity', $item->quantity) }}" required></div><div class="col-6 col-sm-3 col-lg-2"><label class="form-label" for="condition-{{ $item->id }}">Kondisi</label><select class="form-select" id="condition-{{ $item->id }}" name="rows[{{ $item->id }}][condition]" required><option value="good" @selected(old('rows.'.$item->id.'.condition', 'good') === 'good')>Baik</option><option value="damaged" @selected(old('rows.'.$item->id.'.condition') === 'damaged')>Rusak</option></select></div><div class="col-12 col-sm-3 col-lg-3"><label class="form-label" for="note-{{ $item->id }}">Catatan jika tidak sesuai</label><input class="form-control" id="note-{{ $item->id }}" name="rows[{{ $item->id }}][note]" value="{{ old('rows.'.$item->id.'.note') }}" maxlength="500" placeholder="Contoh: selang kurang 1"></div></div>
        @endforeach
        <div class="mt-3"><label class="form-label" for="inspection-note">Catatan umum (opsional)</label><textarea class="form-control" id="inspection-note" name="note" rows="2" maxlength="2000">{{ old('note') }}</textarea></div>
        <div class="mt-3"><button class="btn btn-primary" type="submit">Simpan hasil pengecekan</button></div>
    </form>
    @endif
</div>
<div class="surface"><div class="surface-head"><h2>Riwayat {{ $location->name }}</h2></div><div class="table-responsive"><table class="table"><thead><tr><th>Waktu</th><th>Petugas</th><th>Hasil</th><th></th></tr></thead><tbody>@forelse($history as $inspection)<tr><td>{{ $inspection->created_at->format('d/m/Y H:i') }}</td><td>{{ $inspection->inspector->name }}</td><td><span class="badge-status {{ $inspection->status === 'ok' ? '' : 'is-warm' }}">{{ $inspection->status === 'ok' ? 'Sesuai' : 'Perlu tindak lanjut' }}</span></td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="{{ route('inspections.show', $inspection) }}">Detail</a></td></tr>@empty<tr><td colspan="4" class="empty-state">Belum ada pengecekan untuk lokasi ini.</td></tr>@endforelse</tbody></table></div><div class="p-3">{{ $history->links() }}</div></div>
@endsection
