@extends('layouts.app')
@section('title', 'Permintaan #'.$stockRequest->id)
@section('content')
<div class="page-head"><div><div class="page-eyebrow">{{ strtoupper($stockRequest->item->location->name) }} · PERMINTAAN #{{ $stockRequest->id }}</div><h1 class="page-title">{{ $stockRequest->item->name }}</h1><p class="page-subtitle">Diajukan {{ $stockRequest->created_at->format('d/m/Y H:i') }} oleh {{ $stockRequest->requester->name }}.</p></div><a href="{{ route('requests.index') }}" class="btn btn-outline-secondary">Kembali</a></div>
<div class="row g-3"><div class="col-lg-7"><div class="surface"><div class="surface-head"><h2>Detail permintaan</h2><span class="badge-status">{{ ['submitted'=>'Diajukan','approved'=>'Disetujui','fulfilled'=>'Dipenuhi','rejected'=>'Ditolak'][$stockRequest->status] }}</span></div><div class="surface-body"><dl class="row mb-0"><dt class="col-sm-4">Kode barang</dt><dd class="col-sm-8">{{ $stockRequest->item->sku }}</dd><dt class="col-sm-4">Jumlah diminta</dt><dd class="col-sm-8">{{ $stockRequest->quantity }} {{ $stockRequest->item->unit }}</dd><dt class="col-sm-4">Stok saat ini</dt><dd class="col-sm-8">{{ $stockRequest->item->quantity }} {{ $stockRequest->item->unit }}</dd><dt class="col-sm-4">Keperluan</dt><dd class="col-sm-8">{{ $stockRequest->purpose }}</dd>@if($stockRequest->rejection_note)<dt class="col-sm-4">Alasan ditolak</dt><dd class="col-sm-8">{{ $stockRequest->rejection_note }}</dd>@endif</dl></div></div>
@if($stockRequest->status === 'submitted' && auth()->user()->can('requests.approve'))<div class="surface mt-3"><div class="surface-head"><h2>Keputusan petugas</h2></div><div class="surface-body d-flex flex-wrap gap-2"><form method="post" action="{{ route('requests.transition', [$stockRequest, 'approve']) }}">@csrf<button class="btn btn-primary" type="submit">Setujui</button></form><form method="post" action="{{ route('requests.transition', [$stockRequest, 'reject']) }}" class="d-flex gap-2 flex-wrap">@csrf<input class="form-control" name="note" placeholder="Alasan penolakan" aria-label="Alasan penolakan" required><button class="btn btn-outline-danger" type="submit">Tolak</button></form></div></div>@endif
@if($stockRequest->status === 'approved' && auth()->user()->can('requests.fulfill'))<div class="surface mt-3"><div class="surface-head"><h2>Pengeluaran barang</h2></div><div class="surface-body"><p class="form-hint">Pemenuhan akan mengurangi stok sebesar {{ $stockRequest->quantity }} {{ $stockRequest->item->unit }} dan mencatat mutasi.</p><form method="post" action="{{ route('requests.transition', [$stockRequest, 'fulfill']) }}">@csrf<button class="btn btn-primary" type="submit">Catat barang dikeluarkan</button></form></div></div>@endif
</div><div class="col-lg-5"><div class="surface"><div class="surface-head"><h2>Jejak proses</h2></div><div class="surface-body"><ol class="timeline-plain"><li><strong>Diajukan</strong><div class="form-hint">{{ $stockRequest->created_at->format('d/m/Y H:i') }} · {{ $stockRequest->requester->name }}</div></li>@if($stockRequest->approved_at)<li><strong>Disetujui</strong><div class="form-hint">{{ $stockRequest->approved_at->format('d/m/Y H:i') }} · {{ $stockRequest->approver?->name }}</div></li>@endif @if($stockRequest->fulfilled_at)<li><strong>Dikeluarkan</strong><div class="form-hint">{{ $stockRequest->fulfilled_at->format('d/m/Y H:i') }} · {{ $stockRequest->fulfiller?->name }}</div></li>@endif @if($stockRequest->status === 'rejected')<li><strong>Ditolak</strong><div class="form-hint">{{ $stockRequest->updated_at->format('d/m/Y H:i') }}</div></li>@endif</ol></div></div></div></div>
@endsection
